# Generated by Django 5.2.7 on 2025-10-22 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Biografia')),
                ('profile_image', models.ImageField(default='default_profile.jpg', upload_to='profile_pics', verbose_name='Foto Profilo')),
                ('experience_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzato'), ('professional', 'Professionale')], default='beginner', max_length=20, verbose_name='Livello Esperienza')),
                ('cuisine_specialties', models.JSONField(blank=True, default=list, verbose_name='Specialità Culinarie')),
                ('culinary_interests', models.TextField(blank=True, null=True, verbose_name='Interessi Gastronomici')),
                ('is_public', models.BooleanField(default=True, verbose_name='Profilo Pubblico')),
                ('show_email', models.BooleanField(default=False, verbose_name='Mostra Email')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Località')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data di Nascita')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sito Web')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram')),
                ('total_recipes', models.PositiveIntegerField(default=0)),
                ('total_likes_received', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('accepted', 'Accettata'), ('rejected', 'Rifiutata')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, max_length=200, null=True, verbose_name='Messaggio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
