# Generated by Django 5.2.7 on 2026-03-13 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(default=30, help_text='Tempo in minuti', verbose_name='Tempo Cottura'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine_type',
            field=models.CharField(choices=[('italian', 'Italiana'), ('french', 'Francese'), ('japanese', 'Giapponese'), ('indian', 'Indiana'), ('chinese', 'Cinese'), ('mediterranean', 'Mediterranea'), ('vegan', 'Vegana'), ('vegetarian', 'Vegetariana'), ('dessert', 'Dolce'), ('bread', 'Pane/Lievitato'), ('other', 'Altro')], default='other', max_length=20, verbose_name='Tipo Cucina'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facile'), ('medium', 'Medio'), ('hard', 'Difficile')], default='medium', max_length=10, verbose_name='Difficoltà'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='', verbose_name='Ingredienti'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='', verbose_name='Procedimento'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='personal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Note Personali'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=30, help_text='Tempo in minuti', verbose_name='Tempo Preparazione'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=4, verbose_name='Porzioni'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(choices=[('public', 'Pubblica'), ('friends', 'Solo Amici'), ('private', 'Privata')], default='public', max_length=10, verbose_name='Visibilità'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autore'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_pics', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titolo'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commento')),
                ('is_approved', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recipes.comment')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
