# Generated by Django 5.2.7 on 2026-03-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='total_members',
        ),
        migrations.RemoveField(
            model_name='community',
            name='total_posts',
        ),
    ]
