# Generated by Django 5.2.7 on 2025-10-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_likes_received',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_recipes',
        ),
    ]
